name: bazzite-custom-michael
description: "Golden Image for Michael's RX 9070 / 5800X3D Rig"
base-image: ghcr.io/ublue-os/bazzite-kde
image-version: stable

modules:
  # 1. Copy our custom config files, EDID, and Service Units
  - type: files
    files:
      - usr: /usr
      - etc: /etc

  # 2. Install hardware tools (COSMIC Removed)
  # We removed 'terra-gpg-keys' because our new script handles it manually/correctly.
  - type: rpm-ostree
    install:
      - ryzenadj        # Undervolting Tool
      - alsa-firmware   # G6 Audio Firmware
      - lact            # GPU Tuning Tool

  # 3. Core Apps (System-Wide Flatpaks)
  - type: default-flatpaks
    notify: true
    system: true
    install:
      - com.google.Chrome      # Default Browser
      - dev.vencord.Vesktop    # Discord (Optimized)

# 4. Apply Kernel Args & Tweaks
  - type: script
    scripts:
      - kargs.sh
      - tweaks.sh
      - fix-terra-bootc.sh  # <--- The Final Fix